src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Product;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CommentRepository;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'comments')]
    private $user;

    #[ORM\ManyToOne(targetEntity: Product::class, inversedBy: 'comments')]
    private $product;

    #[ORM\Column(type: 'integer')]
    private $note;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'string', length: 255)]
    private $fullName;

    #[ORM\Column(type: 'datetime_immutable')]
    private $PostedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getPostedAt(): ?\DateTimeImmutable
    {
        return $this->PostedAt;
    }

    public function setPostedAt(\DateTimeImmutable $PostedAt): self
    {
        $this->PostedAt = $PostedAt;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\Column(type: 'float')]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    private $picture;

    #[Vich\UploadableField(mapping: 'pictures', fileNameProperty: 'picture')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'text')]
    private $shortDescription;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'products')]
    private $category;

    #[ORM\Column(type: 'boolean')]
    private $inStock;

    #[ORM\Column(type: 'integer')]
    private $nSell;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: PurchaseItem::class)]
    private $purchaseItems;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Comment::class)]
    private $comments;

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->purchaseItems = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    /**
     * @return Collection<int, category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getInStock(): ?bool
    {
        return $this->inStock;
    }

    public function setInStock(bool $inStock): self
    {
        $this->inStock = $inStock;

        return $this;
    }

    public function getNSell(): ?int
    {
        return $this->nSell;
    }

    public function setNSell(int $nSell): self
    {
        $this->nSell = $nSell;

        return $this;
    }

    /**
     * @return Collection<int, PurchaseItem>
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems[] = $purchaseItem;
            $purchaseItem->setProduct($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getProduct() === $this) {
                $purchaseItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProduct($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getProduct() === $this) {
                $comment->setProduct(null);
            }
        }

        return $this;
    }

}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use DateTimeImmutable;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    #[Route('/{catslug}/{slug}', name: 'product', priority: -2)]
    public function show($slug, ProductRepository $productRepository, CommentRepository $commentRepository, Request $request, EntityManagerInterface $em): Response
    {

        $product = $productRepository->findOneBy([
            'slug' => $slug
        ]);

        if (!$product) {
            $this->addFlash("danger", "Le produit n'a pas été trouvé");
            return $this->redirectToRoute('category_list');
        }

        $comments = $commentRepository->findBy([
            'product' => $product
        ], ['PostedAt' => 'DESC']);

        $form = $this->createForm(CommentType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if (!$product) {
                $this->addFlash("danger", "Le produit n'a pas été trouvé");
                return $this->redirectToRoute('category_list');
            }


            // algo de sécurisation
            $count = 0;
            foreach ($this->getUser()->getPurchases() as $purchase) {
                foreach($purchase->getPurchaseItems() as $item) {
                    if ($item->getProduct() == $product) {
                        $count++;
                    }
                }
            }

            if ($count == 0) {
                $this->addFlash("danger", "Une erreur s'est produite");
                return $this->redirectToRoute('home');
            }
            // fin de la sécu

            $comment = $form->getData()
                ->setUser($this->getUser())
                ->setProduct($product)
                ->setPostedAt(new DateTimeImmutable())
                ->setFullName($this->getUser()->getFirstName() . ' ' . $this->getUser()->getLastName());
            $em->persist($comment);
            $em->flush();

            $this->addFlash("success", "Votre commentaire a bien été ajouté");
            return $this->redirectToRoute('product', [
                'catslug' => 'addcoment',
                'slug' => $slug
            ]);
        }

        $proposedProducts = $productRepository->findBy([], ['nSell' => 'DESC'], 8);

        return $this->render('product/show.html.twig', [
            'product' => $product,
            'comments' => $comments,
            'formview' => $form->createView(),
            'proposedProducts' => $proposedProducts
        ]);
    }

    #[Route('/comment/remove/{id}', name: 'comment_remove')]
    public function commentRemove($id, CommentRepository $commentRepository, EntityManagerInterface $em, ProductRepository $productRepository)
    {
        $comment = $commentRepository->findOneBy([
            'id' => $id
        ]);

        if(!$this->getUser() || !$comment || ($this->getUser() !== $comment->getUser())) {
            $this->addFlash("danger", "Une erreur s'est produite");
            return $this->redirectToRoute('home');
        }

        $product = $comment->getProduct();

        $em->remove($comment);
        $em->flush();

        $this->addFlash("success", "Le commentaire a bien été supprimé");
        return $this->redirectToRoute('product', [
            'catslug' => 'removecomment',
            'slug' => $product->getSlug()
        ]);
    }
}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ product.name }}{% endblock %}

{% block meta_description %}{{ product.name }} - Retrouvez la fiche produit pour {{ product.name }}{% endblock %}

{% block body %}

<div class="row mt-5 text-center">
    <div class="col-12 col-md-12 col-lg-6 mb-4">
        <img src="/uploads/pictures/{{ product.picture }}" class="img-fluid border" alt="{{ product.name }}">
    </div>
    <div class="col-12 col-md-12 col-lg-6 product-description">
        <h2>{{ product.name }}</h2>
        <div class="product-trait mb-2"></div>
            {% if product.inStock == 1 %}
                <div class="d-flex bd-highlight mb-3">
                    <div class="stock-true p-2 bd-highlight"></div>
                    <p class="p-2 bd-highlight">En stock</p>
                    <p class="ms-auto p-2 bd-highlight">Acheté avant 12h (UTC+2), expedié aujourd'hui !</p>
                </div>
            {% else %}
                <div class="d-flex justify-content-start">
                    <div class="stock-false"></div>
                    <p>Rupture de stock !</p>
                </div>
            {% endif %}
            <p>PRIX :</p>
            <p class="product-price">{{ product.price | amount }}</p>
            <p><i class="fas fa-star"></i> &nbsp; Moyenne des avis : 
            {% if comments is not empty %}
                {% set noteCount = 0 %}
                {% set noteTotal = 0 %}
                {% for comment in comments %}
                    {% set noteTotal = noteTotal + comment.note %}
                    {% set noteCount = noteCount + 1 %}
                {% endfor %}
                {{ (noteTotal / noteCount) |round(1, 'floor') }} ({{ noteCount }} avis)
            {% else %}
                pas d'avis
            {% endif %}</p>
            <p><i class="fas fa-tag"></i> &nbsp; Référence DS Music : {{ product.id }}</p>
            {% if product.inStock == 1 %}
                <a href="{{ path('cart_add', {'id': product.id}) }}" class="btn btn-success product-cart-btn"><i class="fas fa-shopping-cart"></i> &nbsp; AJOUTER AU PANIER</a>
            {% endif %}
    </div>
    <div class="product-trait mt-5 mb-4"></div>
    <h4 class="text-center mb-3">DESCRIPTION</h4>
    <p>{{ product.shortDescription }}</p>
    <div class="product-trait mt-5 mb-4"></div>
</div>

{# Sécurité pour eviter bug #}
{% if app.user is not null %}
    {# compteur de vérif si user a déjà acheté cet article #}
    {% set count = 0 %}
    {% for purchase in app.user.purchases %}
        {% for item in purchase.purchaseItems %}
            {% if item.productName == product.name %}
                {% set count = count + 1 %}
            {% endif %}
        {% endfor %}
    {% endfor %}

    {# Compteur de verif si user a déjà posté un commentaire pour cet article #}
    {% set count2 = 0 %}
    {% for comment in app.user.comments %}
        {% if comment.product.id == product.id %}
            {% set count2 = count2 + 1 %}
        {% endif %}
    {% endfor %}

    {% if count > 0 and count2 == 0 %}
        <h3>Mettez un avis sur l'article que vous avez acheté !</h3>

        {{ form_start(formview) }}
        {{form_errors(formview)}}

        {{form_row(formview.note)}}
        {{form_row(formview.content)}}
            <button type="submit" class="btn btn-success">Poster le commentaire</button>
        {{ form_rest(formview) }}
        {{ form_end(formview) }}
        <div class="product-trait mt-4 mb-4"></div>
    {% endif %}
{% endif %}

<h4 class="text-center mb-3">AVIS</h4>
{% if comments is not empty %}
    {% for comment in comments %}
        <p class="mb-4">{{ comment.fullName }}</p>
        {% if comment.note == 1 %}
            <p class="product-card-note mb-4">
                <i class="fas fa-star"></i>
                <i class="fas fa-star grey-star"></i>
                <i class="fas fa-star grey-star"></i>
                <i class="fas fa-star grey-star"></i>
                <i class="fas fa-star grey-star"></i>
            </p>
        {% endif %}
        {% if comment.note == 2 %}
            <p class="product-card-note mb-4">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star grey-star"></i>
                <i class="fas fa-star grey-star"></i>
                <i class="fas fa-star grey-star"></i>
            </p>
        {% endif %}
        {% if comment.note == 3 %}
            <p class="product-card-note mb-4">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star grey-star"></i>
                <i class="fas fa-star grey-star"></i>
            </p>
        {% endif %}
        {% if comment.note == 4 %}
            <p class="product-card-note mb-4">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star grey-star"></i>
            </p>
        {% endif %}
        {% if comment.note == 5 %}
            <p class="product-card-note mb-4">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
            </p>
        {% endif %}
        <p class="comment-date">Publié le {{ comment.postedAt | date('d/m/y H:i') }}</p>
        <p>{{ comment.content }}</p>
        {% if app.user is not null %}
            {% if app.user.id == comment.user.id %}
                <a href="{{ path('comment_remove', {'id': comment.id}) }}" class="btn btn-danger">Supprimer</a>
            {% endif %}
        {% endif %}
        <div class="comment-trait mt-4 mb-4"></div>
    {% endfor %}

{% else %}
    <p class="text-center">Aucun avis n'a encore été publié pour cet article.</p>
{% endif %}

<div class="product-trait mt-4 mb-4"></div>
<div class="row mt-5">
    <h4 class="mt-2 mb-2 text-center">VOUS AIMEREZ AUSSI :</h4>
    {% set category = {'slug': 'bestsells'} %}
    {% for p in proposedProducts %}
        {% include "shared/_productCard.html.twig" %}
    {% endfor %}
</div>

{% endblock %}